# Generated by Django 3.2.5 on 2021-09-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210917_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
