# Generated by Django 3.2.5 on 2021-09-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_reciever_transfer_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='acct',
            field=models.IntegerField(default=0),
        ),
    ]
