# Generated by Django 3.2.5 on 2021-09-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_acct'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='account',
            field=models.IntegerField(default=0),
        ),
    ]
